/**
 * Starts a development server to serve the built assets and static files.
 *
 * Usage:
 *     node scripts/dev-server.ts [--base BASE] [--open]
 *
 * Options:
 *   --base BASE   The base path to serve the application from. Must start and end with `/`. (Default: `/`)
 *   --open        Whether to open the base URL in the default web browser.
 *
 * Example usages:
 *   Start the server at http://localhost:3000/
 *     node scripts/dev-server.ts
 *     node scripts/dev-server.ts --base /
 *   Start the server at http://localhost:3000/news/
 *     node scripts/dev-server.ts --base /news/
 *   Start the server at http://localhost:3000/news/ and open it in the browser
 *     node scripts/dev-server.ts --base /news/ --open
 * 
 * NOTE: This file is generated by AI.
 */

import assert from "node:assert";
import { exec } from "node:child_process";
import { createReadStream, existsSync, statSync } from "node:fs";
import http from "node:http";
import path from "node:path";

const DEFAULT_PORT = 3000;
const DEFAULT_BASE = "/";

type CliOptions = {
  base: `/${string}/` | "/";
  open: boolean;
};

function parseArgs(argv: string[]): CliOptions {
  let base: `/${string}/` | "/" = DEFAULT_BASE;
  let open = false;

  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];

    if (arg === "--base") {
      const next = argv[i + 1];
      if (!next || next.startsWith("--")) {
        throw new Error("--base requires a value");
      }
      base = expectValidBase(next);
      i += 1;
      continue;
    }

    if (arg === "--open") {
      open = true;
      continue;
    }
  }

  return { base, open };
}

function expectValidBase(base: string): `/${string}/` | "/" {
  assert(
    base.startsWith("/") && base.endsWith("/"),
    "--base must be '/' or match '/name/'",
  );
  return base as `/${string}/` | "/";
}

function openBrowser(url: string): void {
  const platform = process.platform;
  let command = "";

  if (platform === "win32") {
    command = `start "" "${url}"`;
  } else if (platform === "darwin") {
    command = `open "${url}"`;
  } else {
    command = `xdg-open "${url}"`;
  }

  exec(command, (error) => {
    if (error) {
      // Ignore browser launch errors to keep the server running.
      return;
    }
  });
}

function contentType(filePath: string): string {
  const ext = path.extname(filePath).toLowerCase();
  switch (ext) {
    case ".html":
      return "text/html; charset=utf-8";
    case ".css":
      return "text/css; charset=utf-8";
    case ".js":
      return "application/javascript; charset=utf-8";
    case ".json":
      return "application/json; charset=utf-8";
    case ".svg":
      return "image/svg+xml";
    case ".png":
      return "image/png";
    case ".jpg":
    case ".jpeg":
      return "image/jpeg";
    case ".woff":
      return "font/woff";
    case ".woff2":
      return "font/woff2";
    default:
      return "application/octet-stream";
  }
}

function getSafeFilePath(rootDir: string, urlPath: string): string | null {
  const decoded = decodeURIComponent(urlPath);
  const safePath = path.normalize(decoded).replace(/^([/\\])+/u, "");
  const resolved = path.resolve(rootDir, safePath);

  if (!resolved.startsWith(rootDir)) {
    return null;
  }

  return resolved;
}

const { base, open } = parseArgs(process.argv.slice(2));
const cwd = process.cwd();
const assetsDir = path.resolve(cwd, "assets");
const distDir = path.resolve(cwd, "dist");

const server = http.createServer((req, res) => {
  if (!req.url) {
    res.writeHead(400);
    res.end("Bad Request");
    return;
  }

  const url = new URL(req.url, `http://localhost:${DEFAULT_PORT}`);
  const requestPath = url.pathname;

  if (!requestPath.startsWith(base)) {
    res.writeHead(404);
    res.end("Not Found");
    return;
  }

  const relativePath = requestPath.slice(base.length);
  const filePath = relativePath.startsWith("assets/")
    ? getSafeFilePath(assetsDir, relativePath.slice("assets/".length))
    : getSafeFilePath(distDir, relativePath);

  if (!filePath) {
    res.writeHead(403);
    res.end("Forbidden");
    return;
  }

  let finalPath = filePath;
  if (existsSync(finalPath) && statSync(finalPath).isDirectory()) {
    finalPath = path.join(finalPath, "index.html");
  }

  if (!existsSync(finalPath)) {
    res.writeHead(404);
    res.end("Not Found");
    return;
  }

  res.writeHead(200, { "Content-Type": contentType(finalPath) });
  createReadStream(finalPath).pipe(res);
});

server.listen(DEFAULT_PORT, () => {
  const baseUrl = `http://localhost:${DEFAULT_PORT}${base}`;
  console.log(`Dev server running at ${baseUrl}`);

  if (open) {
    openBrowser(baseUrl);
  }
});
